version: '3.8'
services:
  mongodb:
    image: mongo:6-jammy
    ports:
      - '27017:27017'
    volumes:
      - dbdata6:/data/db
  backend:
    environment:
      DATABASE_URI: ${DATABASE_URI}
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
volumes:
  dbdata6: